### ISSUE TITLE
Unable to reload webview after update

### ISSUE THREAD

**Issue by Dlr4jobloc** [ionic-team/cordova-plugin-ionic#60] opened 2018-02-09 16:35 UTC
Hi,
i'm trying to update my app with ionic pro  process :
- make a new deploy
- launch my app (download process appends, unzip process too)
- killing my app & restarting it
- logs says : "Reloading the web view." and "Failed to load webpage with error: The operation couldn’t be completed. (NSURLErrorDomain error -999.)"

ios 9.0 on real device / simulator
ionic version 3.19.1
ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.1
    ionic (Ionic CLI) : 3.19.1

global packages:

    cordova (Cordova CLI) : 7.1.0 

local packages:

    @ionic/app-scripts : 3.1.4
    Cordova Platforms  : android 6.3.0 browser 5.0.1 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.13 
    Node       : v6.10.3
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

ionic cordova plugins
> cordova plugin ls
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.9.1 "BackgroundGeolocation"
cordova-fabric-plugin 1.1.10 "cordova-fabric-plugin"
cordova-plugin-add-swift-support 1.7.0 "AddSwiftSupport"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-background-fetch 5.1.1 "CDVBackgroundFetch"
cordova-plugin-calendar 5.0.0 "Calendar"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-file-transfer 1.7.0 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic 3.1.1 "IonicCordova"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-nativegeocoder 2.0.4 "NativeGeocoder"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-sqlite-storage 2.1.4 "Cordova sqlite storage plugin"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.2.5 "OneSignal Push Notifications"
phonegap-plugin-push 2.1.2 "PushPlugin"

Thanks by advance

**Comment by Fuiste** [comment] 2018-02-22 15:28
Can you confirm whether this issue persists in version 4.0.0 of the plugin?

**Comment by HugoHeneault** [comment] 2018-03-13 15:16
@Fuiste I also have this issue using 4.0.0. 

It seems that there is an issue with already opened connections on reload. I'm looking if I can do something, but I'm quite new in iOS dev ;)

**Comment by HugoHeneault** [comment] 2018-03-13 15:23
So I tried something but it didn't work... 

I changed https://github.com/ionic-team/cordova-plugin-ionic/blob/master/src/ios/IonicDeploy.m#L589 by using a `dispatch_after` instead of `dispatch_async` as [some people said it might help](https://stackoverflow.com/a/20280531/1847249)

**Comment by HugoHeneault** [comment] 2018-03-14 18:30
@Fuiste Any luck that you get some time this week to fix it? It's disabling our VoIP push notifications because ionic is not able to run after a deploy... 

I can provide more logs if you want. 

Thanks a lot! :)

**Comment by Fuiste** [comment] 2018-03-15 16:14
From our debugging, it looks like the error is thrown when the app's original `index.html` fails to load, as the deploy plugin is firing off another load for the updated `index`.  Other than the logged error, we have not encountered an issue with the deployed version's ability to apply.

Can you confirm that this error is actually breaking the app?

**Comment by HugoHeneault** [comment] 2018-03-15 22:23
For me, the error is breaking the app on background loading... Do you want some logs from my side? Could I do anything to help you fix this bug? 🤞

**Comment by Fuiste** [comment] 2018-03-28 22:15
Sure thing, if you've got xcode logs I'd definitely take a look, as I've not been able to reproduce this behavior in any of my testing apps.

**Comment by HugoHeneault** [comment] 2018-03-29 06:25
Here is a copy of the message I sent to ionic support: 

> Hi there,
>
> I'm using deploy and it's working great. But I'm also using VoIP push notifications, which wake up the app on background even if it has been force closed.
>
>As long as I don't update my app from deploy the VoIP notifications are working as they should. 
>But as soon as I make an update with deploy, when I receive a notification with the app closed, the app doesn't wake up and stop with this kind of message :
>
>13/03/2018 14:54:43 Tadi[1339]: Failed to load webpage with error: The operation couldn\M-b\M^@\M^Yt be completed. (NSURLErrorDomain error -999.)
>
>It seems that the place where deployed files are stored is not reachable from the app when launched in background from a VoIP notification...
>
>I'm attaching 2 logs : 
>- the 1st before the first update with deploy (from a fresh Testflight installation)
>- the 2nd after a deploy update (from the same Testflight installation, with one deploy update)

[after-deploy.log](https://github.com/ionic-team/cordova-plugin-ionic/files/1858803/after-deploy.log)
[before-deploy.log](https://github.com/ionic-team/cordova-plugin-ionic/files/1858804/before-deploy.log)

**Comment by timbru31** [comment] 2018-04-05 12:43
I can confirm that reloading the app does not work, if the user presses the home button while downloading or extracting the update.

**Comment by HugoHeneault** [comment] 2018-04-10 12:46
Quick update here @Fuiste. The issue might be iPhone-SE related, as my clients, which have different models, don't have this issues. 

Could you try to reproduce on an SE?

Thanks!

**Comment by connor-odoherty** [comment] 2018-04-16 19:28
This is both breaking deploy and Application Directory access upon applying deploy snapshot. Can we get an update here?

**Comment by pverdu** [comment] 2018-04-20 12:43
I'm experiencing the exact same problem. Hope to get an update soon.

**Comment by glebmachine** [comment] 2018-06-23 13:21
Guys, i hope it helps:
https://github.com/glebmachine/cordova-plugin-ionic/commit/7c095a45a13f7349e93f14a3057153775109f635

To install from by fork: 
```
cordova plugin add https://github.com/glebmachine/cordova-plugin-ionic.git#v4
```

**Comment by nphyatt** [comment] 2018-07-24 18:49
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!

**Closed by nphyatt** 2018-07-24 18:49 UTC
