### ISSUE TITLE
App hangs at app screen when installing new binary on top of old binary

### ISSUE THREAD

**Issue by connor-odoherty** [ionic-team/cordova-plugin-ionic#131] opened 2018-08-28 18:41 UTC
**Describe the bug**
When installing a new binary build with updated cordova-plugin-ionic and cordova-plugin-ionic-wkebview over an old binary and snapshot, the app hangs. Killing the app and restarting does not fix it, it enters a permanently broken state that only un-installing can fix.

UPDATE: Even when starting completely fresh (with most recent deploy and wkwebview versions), if my app has taken in a snapshot, it will hang on launch the next time I try to install a new binary on top of it.

BONUS BUG: When starting fresh (making the new binary the first instance of the app) and taking on a snapshot, if you attempt to download an even newer binary on top of it, the changes get reverted back to the old snapshot. This has been reported elsewhere over the past couple weeks, but it is still happening with the new webview and deploy versions.

**To Reproduce**
1. Have an old binary of the app
2. Install a snapshot on top of it
3. Release a new binary with updated deploy and wkebview
4. Update the old binary with the new binary
5. See the splash screen hang without any indication why

**Expected behavior**
The app starts without hanging, and the new binary changes are shown, not the previous snapshot's.

**Platform**
iOS devices

**Additional context**

I am using the NONE deploy method

*Ionic info*
```
Ionic:

   ionic (Ionic CLI)  : 4.1.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.1.11

Cordova:

   cordova (Cordova CLI) : 8.0.0
   Cordova Platforms     : browser 5.0.3, ios 4.5.1
   Cordova Plugins       : cordova-plugin-ionic 5.1.2, cordova-plugin-ionic-webview 2.1.0, (and 19 other plugins)

System:

   ios-deploy : 1.9.2
   ios-sim    : 6.0.0
   NodeJS     : v10.7.0 (/usr/local/Cellar/node/10.7.0/bin/node)
   npm        : 6.2.0
   OS         : macOS High Sierra
   Xcode      : Xcode 9.4.1 Build version 9F2000
```

*Ionic plugins:*
```
com-badrit-base64 0.2.0 "Base64"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-appsee 2.4.1 "Appsee"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-name 1.3.2 "Device-Name"
cordova-plugin-document-viewer 0.9.9 "SitewaertsDocumentViewer"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 5.1.2 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-safariviewcontroller 1.5.4 "SafariViewController"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-themeablebrowser 0.2.17 "ThemeableBrowser"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

*Package.json:*
```
{
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/app-version": "4.7.0",
    "@ionic-native/base64": "4.7.0",
    "@ionic-native/camera": "^4.7.0",
    "@ionic-native/core": "^4.9.2",
    "@ionic-native/device": "^4.7.0",
    "@ionic-native/document-viewer": "4.7.0",
    "@ionic-native/file": "4.9.2",
    "@ionic-native/file-opener": "4.9.2",
    "@ionic-native/file-transfer": "4.9.2",
    "@ionic-native/in-app-browser": "^4.11.0",
    "@ionic-native/ionic-webview": "^5.0.0-beta.14",
    "@ionic-native/keyboard": "4.7.0",
    "@ionic-native/network": "^4.11.0",
    "@ionic-native/pro": "^4.9.2",
    "@ionic-native/safari-view-controller": "^4.11.0",
    "@ionic-native/secure-storage": "^4.7.0",
    "@ionic-native/splash-screen": "4.7.0",
    "@ionic-native/status-bar": "4.7.0",
    "@ionic-native/unique-device-id": "4.7.0",
    "@ionic/app-scripts": "^3.1.11",
    "@ionic/pro": "^2.0.2",
    "@ionic/storage": "2.1.3",
    "body-parser": "^1.18.2",
    "com-badrit-base64": "^0.2.0",
    "connect-wwwhisper": "*",
    "cordova-browser": "5.0.3",
    "cordova-ios": "4.5.1",
    "cordova-plugin-add-swift-support": "^1.7.0",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-camera": "^2.4.1",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-device-name": "^1.3.2",
    "cordova-plugin-document-viewer": "^0.9.9",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-opener2": "^2.0.19",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-ionic": "^5.1.2",
    "cordova-plugin-ionic-webview": "^2.1.0",
    "cordova-plugin-safariviewcontroller": "^1.5.4",
    "cordova-plugin-secure-storage": "^2.6.8",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.1",
    "cordova-plugin-themeablebrowser": "^0.2.17",
    "cordova-plugin-whitelist": "^1.3.3",
    "cors": "^2.8.4",
    "express": "^4.16.2",
    "express-basic-auth": "^1.1.4",
    "heroku-ssl-redirect": "0.0.4",
    "ionic-angular": "^3.9.2",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionic2-auto-complete": "^1.5.2-release",
    "ionic2-super-tabs": "^4.1.4",
    "ionicons": "3.0.0",
    "json-loader": "^0.5.7",
    "jssha": "^2.3.1",
    "lodash": "^4.17.4",
    "logrocket": "^0.6.11",
    "moment": "^2.21.0",
    "moment-timezone": "^0.5.14",
    "morgan": "^1.9.0",
    "node-sass": "^4.9.2",
    "reflect-metadata": "^0.1.10",
    "rxjs": "5.4.0",
    "suncalc": "^1.8.0",
    "sw-toolbox": "3.6.0",
    "typescript": "2.4.0",
    "uglify-js": "^3.3.13",
    "webpack-merge": "^4.1.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/flex-layout": "^2.0.0-beta.12",
    "@types/jssha": "0.0.29",
    "@types/moment": "^2.13.0",
    "@types/moment-timezone": "^0.5.4",
    "tslint": "^5.7.0",
    "ws": "3.3.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-document-viewer": {},
      "cordova-plugin-app-version": {},
      "com-badrit-base64": {},
      "cordova-plugin-device-name": {},
      "cordova-plugin-camera": {
        "CAMERA_USAGE_DESCRIPTION": " ",
        "PHOTOLIBRARY_USAGE_DESCRIPTION": " "
      },
      "cordova-plugin-device": {},
      "cordova-plugin-secure-storage": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-file-opener2": {},
      "cordova-plugin-ionic": {
        "APP_ID": "[[removed]]",
        "CHANNEL_NAME": "“develop”",
        "UPDATE_METHOD": "“none”",
        "WARN_DEBUG": "true",
        "UPDATE_API": "https://api.ionicjs.com",
        "MAX_STORE": "5",
        "MIN_BACKGROUND_DURATION": "30"
      },
      "cordova-plugin-inappbrowser": {},
      "cordova-plugin-safariviewcontroller": {},
      "cordova-plugin-network-information": {},
      "cordova-plugin-themeablebrowser": {},
      "cordova-plugin-ionic-webview": {}
    },
    "platforms": [
      "browser",
      "ios"
    ]
  }
}
```

**Comment by nphyatt** [comment] 2018-08-28 21:36
Thanks for the report! I'll try to reproduce the issue you're having. As for the "Bonus Bug" the only way to control and ensure that the new binaries don't get  overwritten with older snapshots is to use the "native versioning" feature and specify the Maximum binary version that an update should apply to.

**Comment by nphyatt** [comment] 2018-08-29 13:07
@connor-odoherty I was able to verify that this is an issue, although it should only happen in the emulator & device builds launched via XCode and not on real devices getting binary updates from the App Store. (let me know if you've experienced otherwise) The issue is that when you trigger a new build via XCode it updates the system path where files & data get stored. The webview plugin is storing that path so that it can serve the appropriate version of the app and then when XCode changes it the stored path is no longer valid. Will be adding code that detects binary updates and if the path changes and then resets to the bundled version to avoid this. Hopefully we'll have something today but our main developer working on webview plugin is out this week so it may take a couple days. I'll ping you when the fix is available.

**Comment by connor-odoherty** [comment] 2018-08-29 19:29
@nphyatt I am still seeing this issue when downloading binaries purely through test flight and using the updated plugins detailed here: https://ionic.zendesk.com/hc/en-us/articles/360008356194

**Comment by nphyatt** [comment] 2018-08-31 18:58
@connor-odoherty So looks like there was some issues with the way we were loading the app in the webview plugin. For now we made it so that the deploy plugin reloads to the newest version everytime which should fix the issue you were seeing but might be slightly slower to load. Will be working on a longer term better solution but if you would try `5.1.3` and verify if it fixed this issue for you that would be great.

**Comment by connor-odoherty** [comment] 2018-09-04 22:15
@nphyatt If I move from app binary 2.0.0 to 2.0.1 everything works as expected, but downloading a new binary of the same version still causes it to hang.

I understand that in a production environment, users will never download two binaries of the same version, but this is a bit annoying on the dev side. We release multiple binaries with the same version to our testers, but for this to work they must now uninstall and re-login every time we push a new binary for testing

**Comment by nphyatt** [comment] 2018-09-05 12:15
@connor-odoherty I would suggest cutting distinct versions for your testers as well something along the lines of `2.0.0-beta.0`, `2.0.0-beta.1`, etc for pre-releases and `2.0.0`, `2.0.1` etc for production releases. Right now the version is our best way of detecting if something has changed. This should be enough to signal to the plugin that something in the binary has changed.

**Comment by egantz** [comment] 2018-09-05 22:45
Happens also to me, can't figure what really causes this to happen. We have tried to re-install all plugins one-by-one, jumping back and forth in versions but no avail. Any clues? would love to resolve this or at least to assist somehow to solve this once and for all. The inconsistency drives all of our team crazy :0

**Comment by egantz** [comment] 2018-09-05 23:33
Happens also to me, can't figure what really causes this to happen. We have tried to re-install all plugins one-by-one, jumping back and forth in versions but no avail. Any clues? would love to resolve this or at least to assist somehow to solve this once and for all. The inconsistency drives all of our team crazy :(

`ionic info`:
```
cli packages: (/Users/xxxxx/xxxxx/xxxx/xxxxxx/xxxxxx/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 7.0.0 ios 4.5.5
    Ionic Framework   : unknown

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v8.11.3
    npm        : 6.4.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

`cordova plugin ls`:

```
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-applepay 1.1.0 "ApplePay"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-custom-geofence 0.7.7 "geofence"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 2.0.1 "InAppBrowser"
cordova-plugin-ionic 5.1.3 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.2 "PushPlugin"
```

**Comment by nphyatt** [comment] 2018-09-06 20:00
@egantz Try using `cordova-plugin-ionic-webview@2.1.3` and `cordova-plugin-ionic@next` (`5.1.4-2`) Make sure to completely delete the app from the device or simulator prior to testing the new version to clear out any prior state that may be causing an issue. There was a bug prior to `webview@2.1.3` where multiple builds on the simulator would cause issues.

**Comment by nphyatt** [comment] 2018-09-06 20:01
@connor-odoherty Can you try using `cordova-plugin-ionic-webview@2.1.3` and `cordova-plugin-ionic@next` (`5.1.4-2`) I believe they will solve your issues as well.

**Comment by egantz** [comment] 2018-09-06 20:32
Hi @nphyatt thanks for getting back to us!

We just tried to use both latest webview and ionic and unfortunately it still hangs.

Here are some details that may help you help us get there:

`ionic info`:
```
cli packages: (/Users/XXXXX/XXXXX/XXXXXX/XXXXX/XXXXXX/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0
    Gulp CLI              : CLI version 3.9.1 Local version 3.9.1

local packages:

    Cordova Platforms : android 7.0.0 ios 4.5.5
    Ionic Framework   : unknown

System:

    ios-deploy : 1.9.2
    ios-sim    : 6.1.2
    Node       : v8.11.3
    npm        : 6.4.1
    OS         : macOS High Sierra
    Xcode      : Xcode 9.4.1 Build version 9F2000

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro
```

`ionic cordova plugin list`:
```
cordova-plugin-add-swift-support 1.7.1 "AddSwiftSupport"
cordova-plugin-applepay 1.1.0 "ApplePay"
cordova-plugin-browsertab 0.2.0 "cordova-plugin-browsertab"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-custom-geofence 0.7.7 "geofence"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-fullscreen 1.1.0 "cordova-plugin-fullscreen"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-inappbrowser 2.0.1 "InAppBrowser"
cordova-plugin-ionic 5.1.4-2 "cordova-plugin-ionic"
cordova-plugin-ionic-webview 2.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-stripe 1.5.3 "cordova-plugin-stripe"
cordova-plugin-vibration 3.0.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.2.1 "SocialSharing"
es6-promise-plugin 4.1.0 "Promise"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 2.1.2 "PushPlugin"
```

Here's the full Xcode log:
```
2018-09-06 16:27:57.975805-0400 XXXXXX[1138:171456] [Accessibility] ****************** Loading GAX Client Bundle ****************
2018-09-06 16:27:58.123773-0400 XXXXXX[1138:171456] Apache Cordova native platform version 4.5.5 is starting.
2018-09-06 16:27:58.124523-0400 XXXXXX[1138:171456] Multi-tasking -> Device: YES, App: YES
2018-09-06 16:27:58.131607-0400 XXXXXX[1138:171456] CDVWKWebViewEngine: trying to inject XHR polyfill
2018-09-06 16:27:58.183174-0400 XXXXXX[1138:171456] CDVWKWebViewEngine will reload WKWebView if required on resume
2018-09-06 16:27:58.183291-0400 XXXXXX[1138:171456] Using Ionic WKWebView
2018-09-06 16:27:58.184526-0400 XXXXXX[1138:171456] [CDVTimer][console] 0.120044ms
2018-09-06 16:27:58.184714-0400 XXXXXX[1138:171456] [CDVTimer][handleopenurl] 0.120044ms
2018-09-06 16:27:58.186523-0400 XXXXXX[1138:171456] Unlimited access to network resources
2018-09-06 16:27:58.186595-0400 XXXXXX[1138:171456] [CDVTimer][intentandnavigationfilter] 1.816988ms
2018-09-06 16:27:58.186685-0400 XXXXXX[1138:171456] [CDVTimer][gesturehandler] 0.068069ms
2018-09-06 16:27:58.188214-0400 XXXXXX[1138:171456] [CDVTimer][file] 1.493931ms
2018-09-06 16:27:58.192249-0400 XXXXXX[1138:171456] [CDVTimer][splashscreen] 4.004002ms
2018-09-06 16:27:58.192413-0400 XXXXXX[1138:171456] [CDVTimer][ioniccordovacommon] 0.134945ms
2018-09-06 16:27:58.195554-0400 XXXXXX[1138:171456] [CDVTimer][statusbar] 3.105998ms
2018-09-06 16:27:58.196677-0400 XXXXXX[1138:171456] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /private/var/containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2018-09-06 16:27:58.197733-0400 XXXXXX[1138:171456] [MC] Filtering mail sheet accounts for bundle ID: com.XXXXXXapp.app, source account management: 1
2018-09-06 16:27:58.200535-0400 XXXXXX[1138:171456] [CDVTimer][socialsharing] 4.941940ms
2018-09-06 16:27:58.200603-0400 XXXXXX[1138:171456] [CDVTimer][ionicdeeplinkplugin] 0.043035ms
2018-09-06 16:27:58.201490-0400 XXXXXX[1138:171456] [CDVTimer][keyboard] 0.832915ms
2018-09-06 16:27:58.201537-0400 XXXXXX[1138:171456] [CDVTimer][TotalPluginStartup] 17.205954ms
2018-09-06 16:27:58.206736-0400 XXXXXX[1138:171456] createNotificationChecker
2018-09-06 16:27:58.206764-0400 XXXXXX[1138:171456] not coldstart
2018-09-06 16:27:58.274103-0400 XXXXXX[1138:171456] active
2018-09-06 16:27:58.274222-0400 XXXXXX[1138:171456] PushPlugin skip clear badge
2018-09-06 16:27:59.707589-0400 XXXXXX[1138:171456] Got app info: {
    binaryVersionCode = "4.0.0";
    binaryVersionName = "4.0.0";
    bundleName = "com.XXXXXXapp.app";
    bundleVersion = "4.0.0";
    device = "XXXX-XXXX-XXXX-XXXX-XXXX";
    platform = ios;
    platformVersion = "12.0";
    version = "4.0.0";
}
2018-09-06 16:27:59.711207-0400 XXXXXX[1138:171456] WARN: This function has been deprecated in favor of IonicCordova.getAppDetails.
2018-09-06 16:27:59.711294-0400 XXXXXX[1138:171456] DEVICE READY FIRED AFTER 392 ms
2018-09-06 16:27:59.717991-0400 XXXXXX[1138:171456] Got Native app preferences: {
    appId = XXXXXX;
    channel = Dev;
    debug = true;
    host = "https://api.ionicjs.com";
    maxVersions = 2;
    minBackgroundDuration = 30;
    updateMethod = auto;
}
2018-09-06 16:27:59.718034-0400 XXXXXX[1138:171456] No custom config found
2018-09-06 16:27:59.718183-0400 XXXXXX[1138:171456] found some saved prefs doing precedence ops: {
    appId = XXXXXX;
    binaryVersion = "4.0.0";
    binaryVersionCode = "4.0.0";
    binaryVersionName = "4.0.0";
    channel = Dev;
    currentVersionId = "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX";
    debug = true;
    host = "https://api.ionicjs.com";
    maxVersions = 2;
    minBackgroundDuration = 30;
    updateMethod = auto;
    updates =     {
        "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX" =         {
            binaryVersionCode = "4.0.0";
            binaryVersionName = "4.0.0";
            channel = Dev;
            lastUsed = "2018-09-06T16:40:10.898Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/XXXXXX/snapshots/XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX/manifest";
            versionId = "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX";
        };
    };
}
2018-09-06 16:27:59.718286-0400 XXXXXX[1138:171456] Returning saved prefs: {
    appId = XXXXXX;
    binaryVersion = "4.0.0";
    binaryVersionCode = "4.0.0";
    binaryVersionName = "4.0.0";
    channel = Dev;
    currentVersionId = "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX";
    debug = true;
    host = "https://api.ionicjs.com";
    maxVersions = 2;
    minBackgroundDuration = 30;
    updateMethod = auto;
    updates =     {
        "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX" =         {
            binaryVersionCode = "4.0.0";
            binaryVersionName = "4.0.0";
            channel = Dev;
            lastUsed = "2018-09-06T16:40:10.898Z";
            state = ready;
            url = "https://api.ionicjs.com/apps/XXXXXX/snapshots/XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX/manifest";
            versionId = "XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXX";
        };
    };
}
2018-09-06 16:27:59.719230-0400 XXXXXX[1138:171456] Got app info: {
    binaryVersionCode = "4.0.0";
    binaryVersionName = "4.0.0";
    bundleName = "com.XXXXXXapp.app";
    bundleVersion = "4.0.0";
    device = "XXXX-XXXX-XXXX-XXXX-XXXX";
    platform = ios;
    platformVersion = "12.0";
    version = "4.0.0";
}
2018-09-06 16:27:59.722263-0400 XXXXXX[1138:171456] Current: versionCode: 4.0.0 versionName: 4.0.0
2018-09-06 16:27:59.722352-0400 XXXXXX[1138:171456] update: versionCode: 4.0.0 versionName: 4.0.0
2018-09-06 16:27:59.722402-0400 XXXXXX[1138:171456] calling _sync
2018-09-06 16:28:00.325259-0400 XXXXXX[1138:171456] calling _reload
2018-09-06 16:28:00.329106-0400 XXXXXX[1138:171456] done _reloading
error in connection_block_invoke_2: Connection interrupted
```

Let me know how we can help you guys come up with the solution!

As you can imagine, this is time sensitive for us.

Many thanks! 🙏🏻

**Comment by egantz** [comment] 2018-09-06 22:27
@nphyatt 1.3.4 -

![image](https://user-images.githubusercontent.com/4982233/45188473-76f13c80-b202-11e8-9dc5-356268782d24.png)

**Comment by nphyatt** [comment] 2018-09-07 01:45
@egantz I don't think you're experiencing the exact same bug as other people in this issue. Seems like everything is actually loading ok but `cordova.js` is not included in your update that is being applied for some reason. I did try to reproduce on an Ionic 1 app and ran into an issue but it was different from yours so I don't know that it'll solve your issue but you can try `5.1.5` and see if it helps. Otherwise what would help me to debug more would be to get your App ID and the Channel and Snapshot ID (version ID) that your downloading. If you don't want to share publicly you can open a [support ticket](https://ionic.zendesk.com/hc/en-us/requests/new) and refer to this issue and me with the details and support should be able to direct you my way.

**Comment by egantz** [comment] 2018-09-07 18:42
@nphyatt So weird! Ok we just tried to update to `5.1.5` and still, the same result. I will go forward and submit a ticket with all the information. Thanks again!

**Comment by egantz** [comment] 2018-09-12 14:55
OK thanks to @ionic team the problem has been solved. We had for a long time a `cordova.js` file that was part of our bundle and for some reason until version `4.1.7` everything worked fine, passed that version it caused the app to break. We have REMOVED this file and everything works PERFECTLY.

Running version `5.1.6` all seems to work just fine.

Thanks Ionic!

**Comment by nphyatt** [comment] 2018-09-13 14:20
@connor-odoherty closing this issue as I believe it has been resolved. Please reopen if it has not.

**Closed by nphyatt** 2018-09-13 14:20 UTC
Labels: bug, v5
