### ISSUE TITLE
File plugin, Camera plugin, and other plugins that access application directory break after deploying a snaphot

### ISSUE THREAD

**Issue by connor-odoherty** [ionic-team/cordova-plugin-ionic#80] opened 2018-04-20 20:38 UTC
I have an app that downloads files from an external server to the iOS application directory, saves camera images to the application directory, and views these files from the application directory.

When I download my app binary fresh (before applying a snapshot), everything works as expected. However, as soon as a new snapshot is downloaded and applied, all of this functionality breaks.

The interesting part is that everything works again if I kill the app and restart it. 

This break only happens when using WKWebView. It may be related to https://github.com/ionic-team/cordova-plugin-ionic/issues/60#issuecomment-383083813.

Ionic info:

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.2.3 browser 5.0.3 ios 4.5.1
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    ios-sim    : 6.0.0 
    Node       : v8.5.0
    npm        : 5.8.0 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by ltm** [comment] 2018-04-24 14:19
The deploy plugin will change the root of your index.html so if you're using relative URLs to the images in the application directory they'll likely stop working. How are you generating the image URLs?

**Comment by nphyatt** [comment] 2018-07-18 17:36
I believe this was an issue caused by the premature release of a breaking version of `cordova-plugin-ionic-webview`. 

We are about to release a new version of the deploy plugin. Our suggest path for fixing issues in v4 will be upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!

**Comment by nphyatt** [comment] 2018-07-24 18:50
We just released a new version of the deploy plugin. Our suggest path for fixing issues in v4 is upgrading to the new version and we are closing out older issues so that we can better organize and respond to the new ones. The new version is a very big change and brings with it some new features (CDN and smaller update sizes) and lays the groundwork for additional upcoming features. You can [read more about it in our docs](https://ionicframework.com/docs/pro/deploy/api/#try-the-new-improved-deploy-plugin) and learn how to install/upgrade to the new version there.

Thanks for your understanding!

**Closed by nphyatt** 2018-07-24 18:50 UTC
