### ISSUE TITLE
Error while building Android app

### ISSUE THREAD

**Issue by shlomiLan** [ionic-team/cordova-plugin-ionic#160] opened 2018-10-13 11:55 UTC
**cordova plugin ls output:**
```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**ionic info output:**
```
Ionic:

   ionic (Ionic CLI)  : 4.2.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.1.1, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/shlomilanton/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

**Describe the bug**
When running `cordova platform add android --verbose` I get the following error message:
```
Installing "cordova-plugin-ionic" for android
Running command: /Users/shlomilanton/workscpace/slots_tracker_client/platforms/android/cordova/version 
Command finished with error code 0: /Users/shlomilanton/workscpace/slots_tracker_client/platforms/android/cordova/version 
Dependencies detected, iterating through them...
Requesting plugin "cordova-plugin-splashscreen@^5.0.1".
Plugin dependency "cordova-plugin-splashscreen@5.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-splashscreen" already installed on android.
Requesting plugin "cordova-plugin-ionic-webview@^2.1.4".
Failed to install 'cordova-plugin-ionic': CordovaError: Version of installed plugin: "cordova-plugin-ionic-webview@1.1.19" does not satisfy dependency plugin requirement "cordova-plugin-ionic-webview@^2.1.4". Try --force to use installed plugin as dependency.
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:570:49
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Failed to restore plugin "cordova-plugin-ionic" from config.xml. You might need to try adding it again. Error: Version of installed plugin: "cordova-plugin-ionic-webview@1.1.19" does not satisfy dependency plugin requirement "cordova-plugin-ionic-webview@^2.1.4". Try --force to use installed plugin as dependency.
```

**To Reproduce**
1. Delete `platforms/android` folder
2. Run `cordova platform add android --verbose`
3. See error message.

**Expected behavior**
I can't get auto updates to my app and I believe that this is becuse of this error message.

**Comment by jcesarmobile** [comment] 2018-10-13 14:33
You need to use webview 2.xx, uninstall it and reinstall to get latest version

**Comment by shlomiLan** [comment] 2018-10-13 20:07
Thanks for your response.

I have made the update, my `ionic info` is:
```
Ionic:

   ionic (Ionic CLI)  : 4.2.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.1.1, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/shlomilanton/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

But now when I run:
```
cordova plugin add cordova-plugin-ionic --save --variable APP_ID="MY_APP_ID" --variable CHANNEL_NAME="Production" --variable UPDATE_METHOD="background"
```

I get the following error message:
```
Installing "cordova-plugin-ionic" for android
Plugin dependency "cordova-plugin-splashscreen@5.0.2" already fetched, using that version.
Dependent plugin "cordova-plugin-splashscreen" already installed on android.
Failed to install 'cordova-plugin-ionic': CordovaError: Version of installed plugin: "cordova-plugin-ionic-webview@1.1.19" does not satisfy dependency plugin requirement "cordova-plugin-ionic-webview@^2.1.4". Try --force to use installed plugin as dependency.
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:557:37
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:570:49
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Version of installed plugin: "cordova-plugin-ionic-webview@1.1.19" does not satisfy dependency plugin requirement "cordova-plugin-ionic-webview@^2.1.4". Try --force to use installed plugin as dependency.
```

So I run it with `force`
```
cordova plugin add cordova-plugin-ionic --save --variable APP_ID="MY_APP_ID" --variable CHANNEL_NAME="Production" --variable UPDATE_METHOD="background" --force
```

So now I don't get any errors while I'm building the Android app.
But still, I don't see any changes (I updated one of the `.ts` files) in my app after assigning a build to the production channel and relaunching the app.

**Comment by jcesarmobile** [comment] 2018-10-13 20:30
no, you have to uninstall cordova-plugin-ionic-webview 1.1.19 and install cordova-plugin-ionic-webview 2.2.0 (latest at the moment), not force to use the 1.1.19 as the 2.x.x has some new methods required by cordova-plugin-ionic

**Comment by shlomiLan** [comment] 2018-10-13 20:57
This is my current `ionic info`:
```
Ionic:

   ionic (Ionic CLI)  : 4.2.1
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.1
   Cordova Plugins       : cordova-plugin-ionic 5.2.5, cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 1.1.1, (and 6 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/shlomilanton/Library/Android/sdk)
   ios-deploy        : 2.0.0
   NodeJS            : v8.11.3 (/usr/local/bin/node)
   npm               : 6.4.1
   OS                : macOS High Sierra
   Xcode             : Xcode 10.0 Build version 10A255
```

Now I tried:
1.  `npm uninstall cordova-plugin-ionic-webview`
2. `npm install cordova-plugin-ionic-webview`
3. run `cordova plugin add cordova-plugin-ionic --save --variable APP_ID="MY_ADD_ID" --variable CHANNEL_NAME="Production" --variable UPDATE_METHOD="auto"`
4. ` ionic cordova build android --prod` and than copied the app to my phone
5. Made changes in `.ts` file and push change to git
6. Assign new build to `production` channel
7. Reluanch the app, but with no changes.

What I'm missing?
Thanks

**Comment by jcesarmobile** [comment] 2018-10-13 21:00
Why are you using npm install and uninstall? Use cordova plugin rm and cordova plugin add as I told you

**Comment by shlomiLan** [comment] 2018-10-14 19:02
Soory, I missed that. I have made those changes but still no change. 
Is there anyway to debug this process? to see it the "check update" function is been run? instead of uploading it -> assigning the "production" channel -> relaunching the app?

**Comment by jcesarmobile** [comment] 2018-10-19 16:20
This error is because of using an old version of `cordova-plugin-ionic-webview`. If you were able to update to latest version but still doesn't work, create a new issue with the new error if any or more information. Going to close this issue as the problem is you are using an old incompatible version of webview plugin.

**Closed by jcesarmobile** 2018-10-19 16:20 UTC
