### ISSUE TITLE
Ionic Appflow data not saved when using Capacitor

### ISSUE THREAD

**Issue by rrlevy** [ionic-team/cordova-plugin-ionic#228] opened 2019-10-23 21:01 UTC
**cordova plugin ls output:**
N/A

**ionic info output:**
```
Ionic:

   Ionic CLI       : 5.4.4 (/Users/rafaellevy/.nvm/versions/node/v10.16.2/lib/node_modules/ionic)
   Ionic Framework : @ionic/react 4.11.2

Capacitor:

   Capacitor CLI   : 1.2.1
   @capacitor/core : 1.2.1

Utility:

   cordova-res : 0.8.0 
   native-run  : 0.2.8 (update available: 0.2.9)

System:

   NodeJS : v10.16.2 (/Users/rafaellevy/.nvm/versions/node/v10.16.2/bin/node)
   npm    : 6.11.3
   OS     : macOS Mojave
```

**Describe the bug**

When adding Appflow Deploy to a Capacitor project with `ionic deploy add --app-id="YOUR_APP_ID" --channel-name="YOUR_CHANNEL_NAME" --update-method="UPDATE_METHOD"` , the Channel Name and Update Method are not saved anywhere other than the platforms folder.

If you ever need to add a different platform afterwards, or if you are cloning your repo on a new folder, you can't use `ionic deploy add` again, and the new platform will stay without the Appflow information.

**To Reproduce**
1. Create a new Ionic project
2. Add Capacitor to project
3. Build Project `ionic build`
4. Install Android (or any other) platform `npx cap add android`
5. Install AppFlow SDK: `ionic deploy add --app-id="YOUR_APP_ID" --channel-name="YOUR_CHANNEL_NAME" --update-method="auto"`
6. Add ios platform `npx cap add ios`

**Expected behavior**

The Channel Name and Update Method should be saved somewhere in the project folder (probably on `ionic.config.json` together with the appid).

Either the command `ionic deploy add` should work after a new platform is added, or the capacitor project should be updated to copy information from `ionic.config.json` to newly added platforms.

**Comment by rrlevy** [comment] 2019-10-23 21:02
Related to [this issue](https://github.com/ionic-team/capacitor/issues/2091)  posted on capacitor project

**Comment by jcesarmobile** [comment] 2019-10-24 15:56
I moved the other issue to ionic-cli repo https://github.com/ionic-team/ionic-cli/issues/4189

The problem is in ionic-cli, not on the plugin, nor in Capacitor. Closing this one.

**Closed by jcesarmobile** 2019-10-24 15:56 UTC
Labels: triage
